apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team01-QA"
  title: "simplenodeservice-team01-QA"
  description: "Template for the simplenodeservice owned and operated by team01 in environment QA"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team01-QA'
    argocd/app-name: simplenodeservice-team01-QA
  links:
    - url: https://github.com/kendoncowart1/enablement-openpipeline-segments-iam.git
      title: Github Repo
      icon: github
    - url: https://jubilant-space-engine-xpvxpq7xqqp369j4-80.app.github.dev/simplenodeservice-team01-QA
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://jubilant-space-engine-xpvxpq7xqqp369j4-30100.app.github.dev/applications/argocd/simplenodeservice-team01-QA
    - title: View in Dynatrace
      icon: catalog
      url: https://cgv34769.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team01
  lifecycle: QA
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team01"
  description: Group for application team team01
spec:
  type: business-unit
  profile:
    displayName: Team 01
    email: team01@dynatrace.training
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
